#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import numpy as np


def print_hist(values: np.ndarray, bins=20, title="hist"):
    hist, edges = np.histogram(values, bins=bins)
    hist = hist.astype(np.float64)
    hist /= (hist.max() + 1e-9)
    bar_width = 30
    print(f"\n{title}:")
    for i in range(bins):
        left, right = edges[i], edges[i+1]
        bar = "#" * int(hist[i] * bar_width)
        print(f"[{left: .4f}, {right: .4f}): {bar}")


def inspect_pc(pc: np.ndarray, name="pc"):
    # pc: (N, D)
    N, D = pc.shape
    print(f"\n=== {name} distribution ===")
    print(f"shape=(N={N}, D={D}), dtype={pc.dtype}")

    mins = pc.min(axis=0)
    maxs = pc.max(axis=0)
    means = pc.mean(axis=0)
    stds = pc.std(axis=0)

    print("\nPer-dimension stats:")
    for i in range(D):
        print(f"  dim {i:02d}: min={mins[i]: .6f}  max={maxs[i]: .6f}  mean={means[i]: .6f}  std={stds[i]: .6f}")

    # radius to centroid
    center = means
    radii = np.linalg.norm(pc - center, axis=1)
    print("\nRadius-to-centroid stats:")
    print(f"  center(mean)={center}")
    print(f"  radii: min={radii.min():.6f} max={radii.max():.6f} mean={radii.mean():.6f} std={radii.std():.6f}")
    for p in [1,5,10,25,50,75,90,95,99]:
        print(f"  p{p:02d}={np.percentile(radii, p):.6f}")

    print_hist(radii, bins=20, title="Radii histogram (distance to centroid)")


def main():
    ap = argparse.ArgumentParser("Inspect one sample from liche npz generated by generate_random_world_arm_pc.py")
    ap.add_argument("npz_path", type=str)
    ap.add_argument("--index", type=int, default=0, help="sample index")
    ap.add_argument("--path_threshold", type=float, default=0.5,
                    help="threshold to count 'hard path' points")
    args = ap.parse_args()

    data = np.load(args.npz_path, allow_pickle=True)

    # sanity keys
    print("Keys:", list(data.keys()))
    required = ["pc", "labels", "pathlabels"]
    for k in required:
        if k not in data:
            raise KeyError(f"Missing key '{k}' in npz.")

    pc = data["pc"]              # (B, N, D)
    labels = data["labels"]      # (B, N)  0=collision,1=free
    pathlabels = data["pathlabels"]  # (B, N) soft label in [0,1]
    B = pc.shape[0]

    idx = args.index
    if idx < 0 or idx >= B:
        raise IndexError(f"index {idx} out of range [0,{B-1}]")

    print(f"\n=== Using sample {idx}/{B-1} ===")

    pc_i = pc[idx]
    labels_i = labels[idx]
    pathlabels_i = pathlabels[idx]

    # point cloud distribution
    inspect_pc(pc_i, name=f"pc[{idx}] (normalized joint-state point cloud)")

    # label stats
    N = labels_i.shape[0]
    coll_mask = (labels_i == 0)
    free_mask = (labels_i == 1)
    hard_path_mask = (pathlabels_i >= args.path_threshold) & free_mask  # obey collision constraint

    print("\n=== Label statistics ===")
    print(f"Total points: {N}")
    print(f"Collision: {coll_mask.sum()} ({coll_mask.sum()/N*100:.2f}%)")
    print(f"Free:      {free_mask.sum()} ({free_mask.sum()/N*100:.2f}%)")
    print(f"Hard Path (free & pathlabel>={args.path_threshold}): "
          f"{hard_path_mask.sum()} ({hard_path_mask.sum()/N*100:.2f}%)")

    # pathlabel distribution
    print("\n=== Pathlabel distribution ===")
    print(f"min={pathlabels_i.min():.6f} max={pathlabels_i.max():.6f} "
          f"mean={pathlabels_i.mean():.6f} std={pathlabels_i.std():.6f}")
    for p in [0,1,5,10,25,50,75,90,95,99,100]:
        print(f"p{p:02d}={np.percentile(pathlabels_i, p):.6f}")

    print_hist(pathlabels_i, bins=30, title="Pathlabels histogram")

    # optional: inspect path waypoints range
    if "paths" in data:
        paths = data["paths"]  # object array, each entry is (T,D)
        path_i = np.array(paths[idx], dtype=np.float32)
        print("\n=== Path waypoints (normalized) ===")
        print(f"path[{idx}] shape={path_i.shape}")
        print(f"per-dim min={path_i.min(axis=0)}")
        print(f"per-dim max={path_i.max(axis=0)}")

    data.close()


if __name__ == "__main__":
    main()
